<?php 

require_once 'db_connect.php';
require_once 'functions.php';

if (isset($_POST['submit'])){

    $nume=$_POST['nume'];
    $prenume=$_POST['prenume'];
    $email=$_POST['email'];
    $password=$_POST['password'];
    $confirmpassword=$_POST['confirmpassword'];

    $empty_nume=0;
    $invalid_nume=0;
    $empty_prenume=0;
    $invalid_prenume=0;
    $empty_email=0;
    $invalid_email=0;
    $email_exist=0;
    $critical_error=0;
    $empty_password=0;
    $nrcha_password=0;
    $number_password=0;
    $capital_password=0;
    $lowercase_password=0;
    $special_password=0;
    $empty_confirmpassword=0;
    $passworddiff=0;

    if(empty($nume)){
        $empty_nume=1;
    }
    if(validnume($nume)){
        $invalid_nume=1;
    }
    if(empty($prenume)){
        $empty_prenume=1;
    }
    if(validprenume($prenume)){
        $invalid_prenume=1;
    }
    if(empty($email)){
        $empty_email=1;
    }
    if(!filter_var($email, FILTER_VALIDATE_EMAIL)){
        $invalid_email=1;
    }
    if(emailexist($conn, $email)==1){
        $critical_error=1;
    }
    if(emailexist($conn, $email)==2){
        $email_exist=1;
    }
    if(empty($password)){
        $empty_password=1;
    }
    if(validpassword($password)==1){
        $nrcha_password=1;
    }
    if(validpassword($password)==2){
        $number_password=1;
    }
    if(validpassword($password)==3){
        $lowercase_password=1;
    }
    if(validpassword($password)==4){
        $capital_password=1;
    }
    if(validpassword($password)==5){
       $special_password=1;
    }
    if(empty($confirmpassword)){
        $empty_confirmpassword=1;
    }
    if($password !==$confirmpassword){
        $passworddiff=1;
    }
    #todo sterse dupa teste si implementate mai sus
    $error=false;
    if($empty_nume==1){
        $error=true;
        #html+css
        echo"1";
    }
    if($invalid_nume==1){
        $error=true;
        #html+css
        echo"2";
    }
    if($empty_prenume==1){
        $error=true;
        #html+css
        echo"3";
    }
    if($invalid_prenume==1){
        $error=true;
        #html+css
        echo"4";
    }
    if($empty_email==1){
        $error=true;
        #html+css
        echo"5";
    }
    if($critical_error==1){
        $error=true;
        #html+css
        echo"6";
    }
    if($email_exist==1){
        $error=true;
        #html+css
        echo"7";
    }
    if($invalid_email==1){
        $error=true;
        #html+css
        echo"8";
    }
    if($empty_password==1){
        $error=true;
       #html+css
       echo"9";
    }
    if($empty_confirmpassword==1){
        $error=true;
        #html+css
        echo"10";
    }
    if($nrcha_password==1){
        $error=true;
        #html+css
        echo"11";
    }
    if($number_password==1){
        $error=true;
        #html+css
        echo"12";
    }
    if($capital_password==1){
        $error=true;
        #html+css
        echo"13";
    }
    if($lowercase_password==1){
        $error=true;
        #html+css
        echo"14";
    }
    if($special_password==1){
        $error=true;
        #html+css
        echo"15";
    }
    if($passworddiff==1){
        $error=true;
        #html+css
        echo"16";
    }
    #execute actual code
    if($error==false){
        register($conn, $nume, $prenume, $email, $password);
        #html+css
        echo "nu";
    }
}
#<script>
#ajax
#</script>